# Generated by Django 3.1 on 2021-12-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='creted',
            new_name='created',
        ),
    ]
