# Generated by Django 3.1 on 2021-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('image', models.ImageField(default='imges/default.jpg', upload_to='images/')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
