# Generated by Django 3.1 on 2021-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211203_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('surname', models.CharField(max_length=255, verbose_name='Familiya')),
                ('this_born', models.IntegerField(default=0, verbose_name="Tug'ilgan yil")),
                ('born_place', models.CharField(max_length=255, verbose_name="Tug'ilgan joy")),
            ],
            options={
                'verbose_name': 'Qariya',
                'verbose_name_plural': 'Qariyalar',
            },
        ),
    ]
