# Generated by Django 3.1 on 2021-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_elderly'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderly',
            name='image_elderly',
            field=models.ImageField(default='imges/default.jpg', upload_to='images/'),
        ),
    ]
