# Generated by Django 3.1 on 2021-12-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_elderly_image_elderly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('surname', models.CharField(max_length=255, verbose_name='Familiya')),
                ('this_born', models.IntegerField(default=0, verbose_name="Tug'ilgan yil")),
                ('born_place', models.CharField(max_length=255, verbose_name="Tug'ilgan joy")),
                ('image_elderly', models.ImageField(default='imges/default.jpg', upload_to='images/')),
            ],
            options={
                'verbose_name': 'Arxiv',
                'verbose_name_plural': 'Arxivlar',
            },
        ),
    ]
