# Generated by Django 3.1 on 2021-12-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='image_elderly',
            new_name='image_elderly_archive',
        ),
    ]
