# Generated by Django 3.1 on 2021-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_photogalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogalary',
            name='photo_date',
            field=models.DateField(auto_now=True),
        ),
    ]
