# Generated by Django 3.1 on 2021-12-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20211220_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_image', models.ImageField(default='imges/default.jpg', upload_to='images/')),
                ('organ_name', models.CharField(max_length=255)),
                ('organ_position', models.CharField(max_length=255)),
                ('organ_description', models.CharField(max_length=255)),
            ],
        ),
    ]
